
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 30 14:10:43 EET 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 23;
  public static final int FR = 14;
  public static final int LS = 22;
  public static final int KB = 18;
  public static final int RS = 30;
  public static final int CN = 6;
  public static final int FN = 13;
  public static final int WC = 33;
  public static final int CL = 5;
  public static final int DT = 9;
  public static final int AR = 3;
  public static final int ID = 17;
  public static final int LC = 21;
  public static final int AO = 2;
  public static final int FA = 12;
  public static final int ST = 32;
  public static final int LB = 20;
  public static final int RC = 29;
  public static final int RB = 28;
  public static final int MO = 25;
  public static final int PO = 27;
  public static final int EOF = 0;
  public static final int SM = 31;
  public static final int KW = 19;
  public static final int DD = 8;
  public static final int GE = 15;
  public static final int error = 1;
  public static final int BR = 4;
  public static final int HT = 16;
  public static final int DA = 7;
  public static final int EQ = 11;
  public static final int MB = 24;
  public static final int EL = 10;
  public static final int NM = 26;
}

